### ISSUE TITLE
Comma dangle

### ISSUE THREAD

**Issue by jantimon** [namics/eslint-config-namics#1]
<img width="495" alt="error" src="https://cloud.githubusercontent.com/assets/4113649/17617749/17958a54-607c-11e6-9a5d-4858d4dbbccf.png">

Comma dangle decreases the quality of git-history and tends to cause merge conflicts as you have to change lines although you are not changing it.

The rule comes from >=IE7 because IE used to handle the comma dangle as syntax error.
For IE8+/Chrome/FF/Safari/Node that's not and issue anymore.

Do you see further benefits to follow this rules?
I would suggest to turn this rule off.

**Comment by easingthemes** [comment]
Still, it would be good to have some rule about it.

Maybe to use:
`"always-multiline"` requires trailing commas when the last element or property is in a different line than the closing `]` or `}` and disallows trailing commas when the last element or property is on the same line as the closing `]` or `}`

**Comment by jantimon** [comment]
Agreed `"always-multiple"` as suggested by @easingthemes is cleaner than turning it off

**Comment by smollweide** [comment]
Done: [v2.0.0](https://github.com/namics/eslint-config-namics/releases/tag/2.0.0)
