### ISSUE TITLE
compatibility with eslint 4?

### ISSUE THREAD

**Issue by ernscht** [namics/eslint-config-namics#10]
Would it make sense to have eslint 4 support?
Probably it's not that easy, plugins also have to be updated: http://eslint.org/docs/4.0.0/user-guide/migrating-to-4.0.0
What do you think?

**Comment by smollweide** [comment]
- [x] eslint-find-rules
- [ ] eslint-plugin-flowtype (peerDependency eslint >= 2)
- [x] eslint-plugin-import
- [x] eslint-plugin-jsx-a11y
- [x] eslint-plugin-react

**Comment by smollweide** [comment]
https://github.com/namics/eslint-config-namics/releases/tag/4.0.0
