### ISSUE TITLE
compatibility with eslint 5?

### ISSUE THREAD

**Issue by ernscht** [namics/eslint-config-namics#17]
Does it make sense to have eslint 5 support?
[Migration Guide eslint 5](https://eslint.org/docs/user-guide/migrating-to-5.0.0)

What do you think?

**Comment by smollweide** [comment]
Yes, will do it soon

**Comment by smollweide** [comment]
Done with release [6.0.0](https://github.com/namics/eslint-config-namics/releases/tag/6.0.0)
