### ISSUE TITLE
Disallow large imports from JavaScript projects

### ISSUE THREAD

**Issue by danielkoch** [namics/eslint-config-namics#21]
I like the idea of showing tips and improvements into linting errors or warnings. See: https://addyosmani.com/blog/disallow-imports/

What do you think about adding:
1. Such a rule
2. Use some `messages` into our rules. Maybe better only on project basis as a custom rule – because there is a wide range of potentially big libraries out there?

**Comment by smollweide** [comment]
Hi Daniel,
this configuration add a default set of eslint rules. Your are allowed to add additional rules and of cause also plugins to your project.

Hope this is fine for you.
Best regards

**Comment by danielkoch** [comment]
Sure. I think most of the `message`s are always relevant project-only. I only want to remember/keep in mind of those possibility and maybe integrate some `message` into the core in the future.
