### ISSUE TITLE
eslint 6 compatibility

### ISSUE THREAD

**Issue by ernscht** [namics/eslint-config-namics#25]
Some days ago eslint version 6 was released.
Since there are some breaking changes we should invest some time to make tis configuration compatible.

**Comment by smollweide** [comment]
not yet possible because eslint-find-rules does not support it
- https://github.com/sarbbottam/eslint-find-rules/issues/304

**Comment by ernscht** [comment]
eslint-find-rules in version 3.4.0 now suports eslint 6

**Comment by smollweide** [comment]
available with 8.0.0
