### ISSUE TITLE
Conflicting types for different JSX approaches

### ISSUE THREAD

**Issue by adriankremer** [namics/eslint-config-namics#27]
JSX is getting used by other libraries as for now VueJS.
If using a mono-repository with hoisting it will lead to a typescript conflict where it is not able to simultaneously extend "Element" with ReactElement and VNode.

Could we move @types/react and @types/react-dom to devdeps. or create separate packages for different libraries e.g. (@namics/vue-eslint-config)?
Would love to contribute.

**Comment by timmyjs** [comment]
@adriankremer in fact, it is already being planned to create a separate Namics eslint-config for Vue projects. I would be happy if we looked at the topic together.

Did you find a workaround for the issue we could use at the meantime?

**Comment by adriankremer** [comment]
Nevermind it seems to be a general conflict with an unknown origin within mono-repos and the issue i had just disappeared after i excluded storybook stories in the tsconfig..
