### ISSUE TITLE
no-undef errors related to missing globally declared namespaces

### ISSUE THREAD

**Issue by jMergenthal** [namics/eslint-config-namics#30]
With the release of v0.9.3 the version of the typescript eslint plugin and parser got an update from `3.10.1` to `4.8.1` (see [here](https://github.com/namics/eslint-config-namics/commit/96ca5d333cec4a3355e3046e660f6aaf49061692).

It seems that with v4 of typescript-eslint you now have to manually define globally defined namespaces in your configuration file (see [Typescript-eslint FAQ reference](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md#i-get-errors-from-the-no-undef-rule-about-global-variables-not-being-defined-even-though-there-are-no-typescript-errors)).

If you do not do this, eslint will throw `no-undef` related errors although the namespaces are accessible over typescript, e.g.:

```js
const CustomTag = props.tag as keyof JSX.IntrinsicElements; // --> 'JSX' is not defined. eslint(no-undef)
```

So: Does it make sense to apply the recommendation of typescript-eslint, and automatically opt out of the `no-undef` rule altogether as soon as we are using our typescript related configurations?

**Comment by smollweide** [comment]
thank you.
I removed the no-undef rule from the typescript config
